import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SCENARIOS, measureTransition, runAllScenarios, renderReport, SLA_MS } from "./index.js";

test("every scenario resolves to its expected final status", async () => {
  for (const scenario of SCENARIOS) {
    const result = await measureTransition(scenario);
    assert.equal(
      result.finalStatus,
      result.expectedFinalStatus,
      `${scenario.name}: expected ${result.expectedFinalStatus}, got ${result.finalStatus}`,
    );
  }
});

test("every scenario meets the 10-second SLA (REQ-06) — measured, not asserted", async () => {
  for (const scenario of SCENARIOS) {
    const result = await measureTransition(scenario);
    assert.ok(
      result.elapsedMs <= SLA_MS,
      `${scenario.name}: took ${result.elapsedMs}ms, SLA is ${SLA_MS}ms`,
    );
    assert.equal(result.metSla, true);
  }
});

test("a single down probe (no second corroborating tick) does NOT resolve to down", async () => {
  // Guards the corroboration-required-for-down invariant this harness's
  // "up_to_down_requires_two_ticks" scenario documents — a lone failure
  // must not be trusted as `down` within the SLA window.
  const oneTickScenario = {
    name: "single-down-tick-uncorroborated",
    description: "test-only: confirms one failure alone isn't trusted as down",
    ticks: SCENARIOS.find((s) => s.name === "up_to_down_requires_two_ticks")!.ticks.slice(0, 1),
    expectedFinalStatus: "down" as const,
  };
  const result = await measureTransition(oneTickScenario);
  assert.notEqual(result.finalStatus, "down");
  assert.equal(result.finalStatus, "degraded");
});

// Writes to a temp dir, never the tracked report.md — that file is only
// regenerated by `npm run sla-report`, so `npm test` leaves the tree clean.
test("generates and writes the results report", async (t) => {
  const results = await runAllScenarios();
  const report = renderReport(results);
  assert.match(report, /SLA Verification Harness/);
  assert.match(report, /up_to_down_requires_two_ticks/);

  const dir = mkdtempSync(join(tmpdir(), "heimdall-sla-report-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const reportPath = join(dir, "report.md");
  writeFileSync(reportPath, report, "utf-8");
  assert.equal(readFileSync(reportPath, "utf-8"), report);
});
